name: VoidBuilder
version: '1.0-SNAPSHOT'
main: hs.voidbuilder.VoidBuilderPlugin
api-version: '1.21'
authors: [ ___Pumpkinn ]
description: Adds buildable terrain and special mechanics to the void below Y=0